/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desafioeDosQuadros;

import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author patic
 */
public class Trabalho extends javax.swing.JFrame {

    /**
     * Creates new form Trabalho
     */
    public Trabalho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Espelhar o quadro do avião na vertical");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Duplicar o tamanho do quadro da cabeceira da cama");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Virar o quadro de caveira para a esquerda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Deslocar para a direita em 10 colunas o quadro do ciclista");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Rotacionar imagem do quadro da cozinha em 90º");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Diminuir pela metade o tamanho da imagem do quadro do quiosque");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecione a opção desejada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(16, 16, 16)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(13, 13, 13)
                        .addComponent(jButton2)
                        .addGap(16, 16, 16)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
                
        jLabel1.setIcon(null);
        jLabel2.setIcon(null);
	ImageIcon icon=new ImageIcon("src/Imagens/1.png");        
	jLabel1.setIcon(icon);

	BufferedImage image = null; 
        try {
            image = ImageIO.read(new File("src/Imagens/1.png"));
        } catch (IOException ex) {
            Logger.getLogger(Trabalho.class.getName()).log(Level.SEVERE, null, ex);
        }

	AffineTransform tx = AffineTransform.getScaleInstance(1, -1);
	tx.translate(0, -image.getHeight(null));
	AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_NEAREST_NEIGHBOR);
	image = op.filter(image, null);

	jLabel2.setIcon(new ImageIcon(image));	        
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(null);
        jLabel2.setIcon(null);
        ImageIcon icon=new ImageIcon("src/Imagens/4.png");        
        jLabel1.setIcon(icon);
        
	BufferedImage image = null; 
        try {
            image = ImageIO.read(new File("src/Imagens/4.png"));
        } catch (IOException ex) {
            Logger.getLogger(Trabalho.class.getName()).log(Level.SEVERE, null, ex);
        }

        int w=image.getWidth();
        int BufferedImage = 0;
        int h = image.getHeight();
                
                
        BufferedImage dimg = new BufferedImage(w-10, h, image.getType());
        Graphics2D g = dimg.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, // Anti-alias!
            RenderingHints.VALUE_ANTIALIAS_ON);

        g.rotate(Math.toRadians(0), w / 2, h / 2);
        g.drawImage(image, null, 0, 0);
    
        ImageIcon resultado=new ImageIcon(dimg);     
    
	jLabel2.setIcon(resultado);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(null);
        jLabel2.setIcon(null);
	ImageIcon icon=new ImageIcon("src/Imagens/3.png");   
	jLabel1.setIcon(icon);

	BufferedImage image = null; 
        try {
            image = ImageIO.read(new File("src/Imagens/3.png"));
        } catch (IOException ex) {
            Logger.getLogger(Trabalho.class.getName()).log(Level.SEVERE, null, ex);
        }

	AffineTransform tx = AffineTransform.getScaleInstance(-1, 1);
	tx.translate(-image.getWidth(null), 0);
	AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_NEAREST_NEIGHBOR);
	image = op.filter(image, null);
                
	jLabel2.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(null);
        jLabel2.setIcon(null);
	ImageIcon icon=new ImageIcon("src/Imagens/5.png");        
	jLabel1.setIcon(icon);

	int espaco = 0;
	BufferedImage image = null;
        try {
            image = ImageIO.read(new File("src/Imagens/5.png"));
        } catch (IOException ex) {
            Logger.getLogger(Trabalho.class.getName()).log(Level.SEVERE, null, ex);
        }
        int w=image.getWidth();
        //JOptionPane.showConfirmDialog(null, w);
        int BufferedImage = 0;
        int h = image.getHeight();
              //  JOptionPane.showConfirmDialog(null, h);
                /*double angulo = 90;
                Object g = null ;
                //Graphics2D Graphics2D = null;
                
                
                AffineTransform identity = new AffineTransform();
                Graphics2D g2d = (Graphics2D)g;
                AffineTransform trans = new AffineTransform();
                trans.setTransform(identity);
                trans.rotate( Math.toRadians(45) );
                g2d.drawImage(image, trans, this);*/
                
                
                //   g2d.rotate(Math.toRadians( 90 ), image.getWidth()/2., image.getHeight()/2.);
                // g2d.drawImage(image,espaco,espaco,null);
                
        
        BufferedImage dimg = new BufferedImage(w, h, image.getType());
        Graphics2D g = dimg.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, // Anti-alias!
            RenderingHints.VALUE_ANTIALIAS_ON);

        g.rotate(Math.toRadians(90), w / 2, h / 2);

        g.drawImage(image, null, 0, 0);
    
        ImageIcon resultado=new ImageIcon(dimg);     
    //resultado.setImage(icon.getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),1 ));
    
	jLabel2.setIcon(resultado);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(null);
        jLabel2.setIcon(null);
	ImageIcon icon=new ImageIcon("src/Imagens/2.png");        
	jLabel1.setIcon(icon);

	BufferedImage image = null;
        try {
            image = ImageIO.read(new File("src/Imagens/2.png"));
        } catch (IOException ex) {
            Logger.getLogger(Trabalho.class.getName()).log(Level.SEVERE, null, ex);
        }

	int width = image.getWidth();
	int heigth = image.getHeight();
	width = width + width;
	heigth = heigth + heigth;
	BufferedImage imgNew = new BufferedImage(width, heigth, BufferedImage.TYPE_INT_RGB);
	Graphics2D g = imgNew.createGraphics();
	g.drawImage(image, 0, 0, width, heigth, null);
        
        try {
            ImageIO.write(imgNew, "JPG", new File("src/Imagens/9.png"));
        } catch (IOException ex) {
            Logger.getLogger(Trabalho.class.getName()).log(Level.SEVERE, null, ex);
        }

        ImageIcon resultado=new ImageIcon("src/Imagens/9.png");  
        resultado.setImage(icon.getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),1 ));
	jLabel2.setIcon(resultado);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(null);
        jLabel2.setIcon(null);
	ImageIcon icon=new ImageIcon("src/Imagens/6.png");        
	jLabel1.setIcon(icon);
		
	BufferedImage image = null;
        try {
            image = ImageIO.read(new File("src/Imagens/6.png"));
        } catch (IOException ex) {
            Logger.getLogger(Trabalho.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    	int width = image.getWidth();
    	int heigth = image.getHeight();
    	width = width/2;
    	heigth = heigth/2;
        BufferedImage imgNew = new BufferedImage(width, heigth, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = imgNew.createGraphics();
        g.drawImage(image, 0, 0, width, heigth, null);
        try {
            ImageIO.write(imgNew, "JPG", new File("src/Imagens/7.png"));
        } catch (IOException ex) {
            Logger.getLogger(Trabalho.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ImageIcon resultado=new ImageIcon("src/Imagens/7.png");
	jLabel2.setIcon(resultado);	
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabalho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
